### ISSUE TITLE
Net::OpenTimeout

### ISSUE THREAD

**Issue by bytebai920** [ymoyao/cocoapods-privacy#1]
![image](https://github.com/ymoyao/cocoapods-privacy/assets/14013454/d02d9916-ef36-4686-b37c-1bebd30bf2e8)

pod privacy install

**Comment by ymoyao** [comment]
ruby版本需要 >=2.7.0
使用 gem install cocoapods-privacy  安装最新0.3.1 版本(这个版本有限制ruby环境)

**Comment by humbleAna** [comment]
`Net::OpenTimeout - Net::OpenTimeout
/Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:43:in `ssl_socket_connect'
/Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1342:in `connect'
/Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
/Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1237:in `start'
/Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1817:in `request'
/Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1741:in `request_head'`

**Comment by ymoyao** [comment]
> `Net::OpenTimeout - Net::OpenTimeout /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:43:in `ssl_socket_connect' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1342:in `connect' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1248:in `do_start' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1237:in `start' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1817:in `request' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1741:in `request_head'`

看起来像是加载 [github配置文件](https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/config.json) 时存在网络问题，你可以自定义配置来避免这个问题 
1、下载 https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/config.json 和 https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/NSPrivacyAccessedAPITypes.plist   文件，并将其都上传到你们自己服务器，转成自己服务器的链接
2、 替换config.json 中 ‘api.template.url’ NSPrivacyAccessedAPITypes.plist 文件地址 为自己服务器文件地址
3、重新执行配置命令 pod privacy config ‘自身服务器地址/config.json’

需要注意的是，之后每次更改config 都需要重新执行配置命令，但如果只是更改 NSPrivacyAccessedAPITypes.plist 文件 ，则无需任何操作，插件内部会自动判断其是否更新，从而自动下载～

**Comment by wcsdn** [comment]
> > `Net::OpenTimeout - Net::OpenTimeout /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:43:in `ssl_socket_connect' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1342:in `connect' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1248:in `do_start' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1237:in `start' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1817:in `request' /Users/yyh/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/http.rb:1741:in `request_head'`
> 
> 看起来像是加载 [github配置文件](https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/config.json) 时存在网络问题，你可以自定义配置来避免这个问题 1、下载 https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/config.json 和 https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/NSPrivacyAccessedAPITypes.plist 文件，并将其都上传到你们自己服务器，转成自己服务器的链接 2、 替换config.json 中 ‘api.template.url’ NSPrivacyAccessedAPITypes.plist 文件地址 为自己服务器文件地址 3、重新执行配置命令 pod privacy config ‘自身服务器地址/config.json’
> 
> 需要注意的是，之后每次更改config 都需要重新执行配置命令，但如果只是更改 NSPrivacyAccessedAPITypes.plist 文件 ，则无需任何操作，插件内部会自动判断其是否更新，从而自动下载～

Errno::ECONNREFUSED - Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)

**Comment by wcsdn** [comment]
/Users/xxx/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String: "execution expired" (FrozenError)
