### ISSUE TITLE
ruby-3.0.0 ， cocapods-1.15  版本报错 ~  

### ISSUE THREAD

**Issue by Angelnil** [ymoyao/cocoapods-privacy#11]
TypeError - no implicit conversion of nil into String
/Users/XXXXXX/.rvm/gems/ruby-3.0.0/gems/cocoapods-privacy-0.5.3/lib/cocoapods-privacy/privacy/PrivacyUtils.rb:30:in `extname'
/Users/XXXXXX/.rvm/gems/ruby-3.0.0/gems/cocoapods-privacy-0.5.3/lib/cocoapods-privacy/privacy/PrivacyUtils.rb:30:in `project_code_fold'
/Users/XXXXXX/.rvm/gems/ruby-3.0.0/gems/cocoapods-privacy-0.5.3/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:127:in `privacy_handle'
/Users/XXXXXX/.rvm/gems/ruby-3.0.0/gems/cocoapods-privacy-0.5.3/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:72:in `install!'
/Users/XXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/XXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/XXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.0/lib/cocoapods/command.rb:52:in `run'
/Users/XXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.0/bin/pod:55:in `<top (required)>'
/Users/XXXXXX/.rvm/rubies/ruby-3.0.0/bin/pod:25:in `load'
/Users/XXXXXX/.rvm/rubies/ruby-3.0.0/bin/pod:25:in `<main>'
/Users/XXXXXX/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/XXXXXX/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

**Comment by Angelnil** [comment]
是因为我都是本地 pod 么 。我先改成远程pod 试试
